[build]
base = "examples/app"
publish = "dist"
command = "curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash && cargo binstall trunk && trunk build --release"
environment = { NETLIFY_EXPERIMENTAL_BUILD_RUST_SOURCE = "true" }
