[package]
name = "app"
edition = "2024"
publish = false

[dependencies]
console_error_panic_hook = "0.1.7"
dotenvy_macro = "0.15.7"
iced = { version = "0.13.1", features = ["webgl", "fira-sans", "tokio"] }
pusher_client = { path = "../../", default-features = false }
